### PR TITLE
added deleteClient method

### LINKED ISSUE #2: Feature to remove clients
Hello!

I'm using snapweb in a home-assistant add-on here: https://github.com/uSpike/hassio-addons/tree/master/snapserver

I find that I have some clients that I'd like to delete since they have been removed from my system.  I'd much rather have a way to remove them from the web interface, instead of what I have to do now and edit the server's .json file directly.

Cheers!

### PR DESCRIPTION
**Pull request by TekniskSupport**
Should fix #2

### CODE REVIEW

**Comment by badaix** [comment]
Thanks,

I tried it out and found some issues:
1. The edit button and the speaker button positions are swapped. In your version it looks like this:
image
but it should like this:
image

2. Delete doesn't work for me, there is always the edit dialog opened, for online as well as for offline clients

3. It should still be possible to edit offline clients, I would rather place a delete button on the edit dialog for offline clients

4. The `deleted` field in the client struct is not really needed, you can 
    1. Send the delete request to the server
    2. Remove the deleted client from the group (instead of setting the client's `deleted` flag to true)
    3. In `show()` you don't have to care about the deleted client, because it has just been removed in step 2 and is gone
    4. The response to the delete request will be a complete server state message, with information about groups, clients and Streams. This response could be used to refresh the internal data structure and to call `show()` again (the deleted client will be gone), or the response could be ignored, because it should be the same as in (iii.).

**Comment by TekniskSupport** [comment]
Hi,

Not really sure why the icons are off for you, this is what it looks like for me, could it be that the CSS is cached?
image
Which browser are you using?

For me it works as expected.
I know that the deleted flag was a bit of a hack, i'll look into another way of solvving it.

Kind regads Iesus

**Comment by badaix** [comment]
Sorry, I see now what went wrong: I've updated to your repo and ran the typescript compiler, so the `script.js` got overwritten by the transpiled `script.ts`, and I've ended up using the original script and your css :)
I should remove the generated javascript files from the project to avoid confusion. Can you please apply your changes to the `script.ts`?

**Comment by TekniskSupport** [comment]
@badaix Oh, sorry guess i didn't look properly, added the code to the typescript file

**Comment by badaix** [comment]
Now I'm getting this: 

```
script.ts:283:46 - error TS7006: Parameter 'group' implicitly has an 'any' type.

283         this.server.groups.forEach((function(group, gi) {
                                                 ~~~~~

script.ts:283:53 - error TS7006: Parameter 'gi' implicitly has an 'any' type.

283         this.server.groups.forEach((function(group, gi) {
                                                        ~~

script.ts:284:41 - error TS7006: Parameter 'client' implicitly has an 'any' type.

284         group.clients.forEach((function(client, ci) {
                                            ~~~~~~

script.ts:284:49 - error TS7006: Parameter 'ci' implicitly has an 'any' type.

284         group.clients.forEach((function(client, ci) {
                                                    ~~

script.ts:287:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

287                 this.server.groups[gi].clients = group.clients;
                    ~~~~

script.ts:289:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

289         }).bind(this))
                    ~~~~

  script.ts:283:37
    283         this.server.groups.forEach((function(group, gi) {
                                            ~~~~~~~~
    An outer value of 'this' is shadowed by this container.

script.ts:292:42 - error TS7006: Parameter 'groups' implicitly has an 'any' type.

292     this.server.groups.forEach((function(groups, gi) {
                                             ~~~~~~

script.ts:292:50 - error TS7006: Parameter 'gi' implicitly has an 'any' type.

292     this.server.groups.forEach((function(groups, gi) {
                                                     ~~

script.ts:294:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

294                 this.server.groups.splice(gi,1);
                    ~~~~

  script.ts:292:33
    292     this.server.groups.forEach((function(groups, gi) {
                                        ~~~~~~~~
    An outer value of 'this' is shadowed by this container.


Found 9 errors.
```

**Comment by TekniskSupport** [comment]
Hi 

What transpiler are you using, i used tsc 2.7.2 and got no errors,
 but the output was a bit different from the already transpiled file so i guess you are using something else?

**Comment by badaix** [comment]
I'm using 3.9.2

**Comment by TekniskSupport** [comment]
Sorry for the many turns, now seems to compile with 3.9.2
image

/i

**Comment by badaix** [comment]
Getting this now:

```
$ tsc
script.ts:284:9 - error TS7053: Element implicitly has an 'any' type because expression of type '"clients"' can't be used to index type '{}'.
  Property 'clients' does not exist on type '{}'.

284         group["clients"].forEach((function(client: object, ci: number) {
            ~~~~~~~~~~~~~~~~

script.ts:285:17 - error TS7053: Element implicitly has an 'any' type because expression of type '"id"' can't be used to index type '{}'.
  Property 'id' does not exist on type '{}'.

285             if (client["id"] == client_id) {
                    ~~~~~~~~~~~~

script.ts:286:17 - error TS7053: Element implicitly has an 'any' type because expression of type '"clients"' can't be used to index type '{}'.
  Property 'clients' does not exist on type '{}'.

286                 group["clients"].splice(ci,1);
                    ~~~~~~~~~~~~~~~~

script.ts:287:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

287                 this.server.groups[gi].clients = group["clients"];
                    ~~~~

script.ts:287:50 - error TS7053: Element implicitly has an 'any' type because expression of type '"clients"' can't be used to index type '{}'.
  Property 'clients' does not exist on type '{}'.

287                 this.server.groups[gi].clients = group["clients"];
                                                     ~~~~~~~~~~~~~~~~

script.ts:289:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

289         }).bind(this))
                    ~~~~

  script.ts:283:37
    283         this.server.groups.forEach((function(group: object, gi: number) {
                                            ~~~~~~~~
    An outer value of 'this' is shadowed by this container.

script.ts:292:32 - error TS2345: Argument of type '(groups: Object[], gi: number) => void' is not assignable to parameter of type '(value: Group, index: number, array: Group[]) => void'.
  Types of parameters 'groups' and 'value' are incompatible.
    Type 'Group' is missing the following properties from type 'Object[]': length, pop, push, concat, and 28 more.

292     this.server.groups.forEach((function(groups: Array<Object>, gi: number) {
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
293             if (groups["clients"].length == 0) {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
295             }
    ~~~~~~~~~~~~~
296         }).bind(this));
    ~~~~~~~~~~~~~~~~~~~~~

script.ts:293:24 - error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

293             if (groups["clients"].length == 0) {
                           ~~~~~~~~~

script.ts:294:17 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

294                 this.server.groups.splice(gi,1);
                    ~~~~

  script.ts:292:33
    292     this.server.groups.forEach((function(groups: Array<Object>, gi: number) {
                                        ~~~~~~~~
    An outer value of 'this' is shadowed by this container.


Found 9 errors.
```
I think that `tsc script.ts` will ingore `tsconfig.json`, and thus use different settings (no strict typing)

**Comment by TekniskSupport** [comment]
Oh ok, i understand.
Havn't used typescript before XD

I'll give it a try to fix the errors, finally getting same errors as you :)

**Comment by TekniskSupport** [comment]
Ok, try now.
 i think I finally got it sorted

**Comment by badaix** [comment]
Looks good now :)
Thanks!
